apiVersion: v1
kind: ConfigMap
metadata:
  name: application-configs
data:
  test.sh: |
    #!/bin/bash
    valid=true
    count=1
    while [ $valid ]
    do
      echo $count
      echo "$(date +%F'  ||  '%R:%S'  ||--') current count value:$count" >> $(hostname).log
      if [ $count -eq 50 ];
        then
          break
      fi
      sleep 2
      count=$((count+1))
    done
