apiVersion: v1
kind: ConfigMap
metadata:
  name: application-configs
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"

  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
  test.sh: |
    #!/bin/bash
    valid=true
    count=1
    while [ $valid ]
    do
      echo $count
      echo "$(date +%F'  ||  '%R:%S'  ||--') current count value:$count" >> $(hostname).log
        if [ $count -eq 50 ];
	  then
	    break
	fi
	sleep 2
	((count++))
    done

