apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  containers:
  - image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    name: elasticsearch
    command: ["/bin/sh"]
    args: ["-c", "echo $MY_POD_NAMESPACE > /tmp/letscheckpodnamespace.txt; env >> /tmp/letscheckpodnamespace.txt; sleep 3600"]
    env:
      - name: MY_POD_NAMESPACE
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.namespace
      - name: node.name
        value: "testnodees01"
      - name: cluster.name
        value: "es-docker-cluster"
      - name: discovery.seed_hosts
        value: "testnodees01"
      - name: bootstrap.memory_lock
        value: "true"
      - name: ES_JAVA_OPTS
        value: "-Xms512m -Xmx512m"
      - name: discovery.type
        value: "single-node"
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - name: volume-shared-logs
        mountPath: /logs
      - name: volume-app-configs
        mountPath: /app/config
  restartPolicy: Always
  volumes:
    - name: volume-app-configs
      configMap:
        name: application-configs
        defaultMode: 420
    - name: volume-shared-logs
      emptyDir: {}
